// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountInfo } from "./AccountInfo";

export type AccountStatus = { 
/**
 * Der letzte erfolgreich gelesene Stand; `None` vor dem ersten Lesen. Ein gescheitertes Lesen
 * lässt ihn stehen.
 */
info: AccountInfo | null, 
/**
 * Fehler des letzten Lesens, `None` nach einem Erfolg.
 */
error: string | null, isLoggingIn: boolean, };
