// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountInfo = { loggedIn: boolean, email: string | null, orgName: string | null, 
/**
 * `subscriptionType`, z.B. `pro`.
 */
plan: string | null, 
/**
 * `authMethod`, z.B. `claude.ai`.
 */
authMethod: string | null, };
