// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArchiveSnippet } from "./ArchiveSnippet";

export type ArchivedProject = { id: string, name: string, createdAt: number, archivedAt: number, sessionCount: number, 
/**
 * Namen der Repositories in Positions-Reihenfolge, aus der Session mit der kleinsten Nummer.
 */
repositoryNames: Array<string>, 
/**
 * Leer ohne Suchbegriff oder wenn nur der Name des Vorhabens passt.
 */
snippets: Array<ArchiveSnippet>, };
