// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ein Ausschnitt um eine Fundstelle im Chat, ohne Zeilenumbrüche.
 */
export type ArchiveSnippet = { sessionName: string, text: string, };
