// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArchivedProject } from "./ArchivedProject";

export type ArchivePage = { items: Array<ArchivedProject>, 
/**
 * Nach dieser Seite passt noch mindestens ein weiteres Vorhaben.
 */
hasMore: boolean, };
