// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Artifact } from "./Artifact";

export type ArtifactList = { 
/**
 * Absoluter Pfad des Ordners `.artefakte`, auch wenn es ihn noch nicht gibt.
 */
dir: string, 
/**
 * Adresse des Ordners auf dem Artefakt-Server, mit `/` am Ende; dahinter folgt der
 * prozent-kodierte Dateiname. Gilt nur, solange die App läuft (Zufalls-Port und -Token).
 */
baseUrl: string, 
/**
 * Neueste Änderung zuerst.
 */
items: Array<Artifact>, };
