// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Artifact = { 
/**
 * Dateiname im Ordner, z. B. "quartalsbericht-q3.html".
 */
file: string, 
/**
 * Inhalt von <title>, sonst der Dateiname ohne Endung.
 */
title: string, 
/**
 * Letzte Änderung der Datei, ms seit 1970.
 */
modifiedAt: number, 
/**
 * Session des Vorhabens, die die Datei zuletzt mit einem schreibenden Werkzeug angefasst hat
 * (Tabelle `session_files`); `None`, wenn keine (z. B. per Shell geschrieben).
 */
sessionId: string | null, sessionNumber: number | null, sessionName: string | null, };
