// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Artifact } from "./Artifact";

export type ArtifactList = { 
/**
 * Absoluter Pfad des Ordners `.artefakte`, auch wenn es ihn noch nicht gibt.
 */
dir: string, 
/**
 * Neueste Änderung zuerst.
 */
items: Array<Artifact>, };
