// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `Image` richtet sich nur nach der Endung — ob ein Bild als Inhalt oder als Pfad an den
 * Agenten geht, entscheidet zusätzlich seine Größe (`attachments::message_content`).
 */
export type AttachmentKind = "image" | "file";
