// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackgroundKind } from "./BackgroundKind";
import type { BackgroundState } from "./BackgroundState";
import type { SubagentStep } from "./SubagentStep";

export type BackgroundItem = { 
/**
 * `task_id` bei Prozess und Subagent, `tool_use_id` beim Befehl.
 */
id: string, 
/**
 * Verbindet den Eintrag mit der Werkzeug-Zeile im Chat.
 */
toolUseId: string, kind: BackgroundKind, state: BackgroundState, 
/**
 * Der Befehl (Befehl, Prozess) bzw. die Aufgabe (Subagent).
 */
title: string, 
/**
 * Millisekunden seit der Epoche.
 */
startedAt: number, endedAt: number | null, exitCode: number | null, url: string | null, outputFile: string | null, subagentType: string | null, 
/**
 * Modell-ID, wie die Kommandozeile sie meldet.
 */
model: string | null, toolUses: number, 
/**
 * Höchstens die letzten 200; ältere fallen weg.
 */
steps: Array<SubagentStep>, result: string | null, };
