// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `Interrupted`: der Agent-Prozess endete, während der Eintrag lief. Er kann trotzdem
 * weitergelaufen sein — deshalb gibt es bewusst kein „nicht ausgeführt“.
 */
export type BackgroundState = "running" | "completed" | "failed" | "stopped" | "interrupted";
