// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Blickwinkel auf die Änderungen, alle gegen die Basis des Eintrags (ADR 006): `base_commit` der
 * Session, bei einem Ticket-Worktree seine Abzweigung vom Standard-Branch.
 */
export type ChangeScope = "all" | "committed" | "uncommitted";
