// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Blickwinkel auf die Änderungen, alle gegen `base_commit` der Session (ADR 006).
 */
export type ChangeScope = "all" | "committed" | "uncommitted";
