// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatEntry } from "./ChatEntry";

export type ChatPage = { entries: Array<ChatEntry>, hasMore: boolean, };
