// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attachment } from "./Attachment";
import type { Question } from "./Question";
import type { QuestionKind } from "./QuestionKind";
import type { ReviewComment } from "./ReviewComment";
import type { SkillRef } from "./SkillRef";
import type { TodoItem } from "./TodoItem";
import type { ToolState } from "./ToolState";

/**
 * Ein Eintrag im Chat-Verlauf. `seq` ist sein Index in der Session; ein geänderter
 * Eintrag behält seine `seq` und wird erneut gesendet.
 */
export type ChatEntry = { "kind": "user", seq: number, text: string, sentAt: number, 
/**
 * Einträge aus der Zeit vor Anhängen haben das Feld nicht.
 */
attachments: Array<Attachment>, 
/**
 * Der Skill, den die Nachricht mit `/name` aufruft.
 */
skill: SkillRef | null, 
/**
 * Review-Kommentare aus der Changes-Ansicht; Einträge von vorher haben das Feld nicht.
 */
comments: Array<ReviewComment>, } | { "kind": "text", seq: number, text: string, } | { "kind": "thinking", seq: number, text: string, seconds: number, } | { "kind": "tool", seq: number, toolUseId: string, tool: string, target: string, state: ToolState, } | { "kind": "todos", seq: number, items: Array<TodoItem>, } | { "kind": "question", seq: number, requestId: string, questionKind: QuestionKind, questions: Array<Question>, answer: string | null, } | { "kind": "error", seq: number, title: string, text: string, };
