// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatEntry } from "./ChatEntry";

export type ChatEntryEvent = { sessionId: string, entry: ChatEntry, };
