// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ergebnis des letzten `claude update` in dieser App-Sitzung.
 */
export type CliUpdateOutcome = { succeeded: boolean, 
/**
 * Die letzten Zeilen der Ausgabe von `claude update`.
 */
output: string, };
