// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CliUpdateOutcome } from "./CliUpdateOutcome";

export type CliVersionStatus = { 
/**
 * Die installierte Version, z.B. `2.1.284`; `None`, wenn sie sich nicht lesen ließ.
 */
installed: string | null, 
/**
 * Die jüngste veröffentlichte Version; `None`, wenn die Abfrage scheiterte.
 */
latest: string | null, 
/**
 * `true`, nur wenn beide Versionen bekannt sind und `latest` neuer ist.
 */
hasUpdate: boolean, isUpdating: boolean, lastUpdate: CliUpdateOutcome | null, 
/**
 * Fehler beim Lesen der installierten Version.
 */
installedError: string | null, 
/**
 * Fehler bei der Abfrage der jüngsten Version.
 */
latestError: string | null, };
