// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `System` folgt der Windows-Einstellung für hell oder dunkel.
 */
export type ColorScheme = "dark" | "light" | "system";
