// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fehler, den ein Tauri Command an die Oberfläche meldet.
 * Nutzer-relevante Fälle bekommen eigene Varianten, damit die UI eine passende Aktion anbieten kann.
 */
export type CommandError = { "kind": "internal", "message": string } | { "kind": "sessionNotFound", "message": string } | { "kind": "claudeNotFound" } | { "kind": "sessionClosed" } | { "kind": "agentStopped" } | { "kind": "io", "message": string } | { "kind": "database", "message": string } | { "kind": "gitNotFound" } | { "kind": "git", "message": string } | { "kind": "repositoryMissing", "message": string } | { "kind": "folderNotAllowed", "message": string } | { "kind": "attachmentsWhileWaiting" } | { "kind": "commentsWhileWaiting" } | { "kind": "voiceModelMissing" } | { "kind": "voiceBusy" } | { "kind": "microphone", "message": string } | { "kind": "noAudio" } | { "kind": "noSpeech" } | { "kind": "voiceCancelled" } | { "kind": "voiceDownload", "message": string };
