// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fehler, den ein Tauri Command an die Oberfläche meldet.
 * Nutzer-relevante Fälle bekommen später eigene Varianten (siehe rust.md).
 */
export type CommandError = { "kind": "internal", "message": string };
