// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextCategory } from "./ContextCategory";
import type { ContextFile } from "./ContextFile";

export type ContextBreakdown = { model: string, totalTokens: number, maxTokens: number, 
/**
 * Nur `kind` `used` und `free`, in der Reihenfolge der Kommandozeile; `deferred` fällt weg.
 */
categories: Array<ContextCategory>, memoryFiles: Array<ContextFile>, 
/**
 * `None`, wenn `isAutoCompactEnabled` nicht `true` ist oder der Wert fehlt.
 */
autoCompactThreshold: number | null, 
/**
 * Millisekunden seit 1970; gesetzt beim Eintreffen im Core.
 */
fetchedAt: number, };
