// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffLineKind } from "./DiffLineKind";

export type DiffLine = { kind: DiffLineKind, 
/**
 * Nummer in der alten Fassung; fehlt bei Hinzugefügtem und Abschnittsköpfen.
 */
oldLine: number | null, 
/**
 * Nummer in der neuen Fassung; fehlt bei Gelöschtem und Abschnittsköpfen.
 */
newLine: number | null, 
/**
 * Ohne Vorzeichen und ohne Zeilenende.
 */
text: string, };
