// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineStat } from "./LineStat";

/**
 * Eine geänderte Datei mit ihren Zahlen je Blickwinkel; fehlt ein Wert, ist sie dort unverändert.
 */
export type FileChange = { 
/**
 * Relativ zum Worktree, mit Schrägstrichen.
 */
path: string, all: LineStat | null, committed: LineStat | null, uncommitted: LineStat | null, };
