// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffLine } from "./DiffLine";

export type FileDiff = { lines: Array<DiffLine>, 
/**
 * Kein Textvergleich möglich; `lines` ist dann leer.
 */
binary: boolean, 
/**
 * `lines` endet nach der Höchstzahl an Zeilen.
 */
truncated: boolean, };
