// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Eine Session des Vorhabens, die gerade arbeitet und damit die Sperre hält.
 */
export type GitBusySession = { id: string, number: number, name: string, };
