// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitBranch = { 
/**
 * Lokal `x`, remote `origin/x`.
 */
name: string, remote: boolean, current: boolean, 
/**
 * Ordnername des Worktrees, in dem der Branch anderswo ausgecheckt ist.
 */
worktree: string | null, };
