// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitForeignFile } from "./GitForeignFile";
import type { GitOperation } from "./GitOperation";
import type { GitOwnCommit } from "./GitOwnCommit";

/**
 * Der Git-Zustand eines Eintrags der Changes. Scheitert das Lesen, steht nur `error`, der Rest ist
 * leer bzw. 0.
 */
export type GitEntryStatus = { 
/**
 * `RepositoryChanges.key`.
 */
key: string, 
/**
 * `None` bei losgelöstem HEAD.
 */
branch: string | null, 
/**
 * Z. B. `origin/main`.
 */
upstream: string | null, 
/**
 * Ziel für einen Push ohne Upstream: `origin`, sonst der einzige Remote.
 */
remote: string | null, ahead: number, behind: number, operation: GitOperation, conflicted: Array<string>, foreign: Array<GitForeignFile>, 
/**
 * Neueste zuerst.
 */
commits: Array<GitOwnCommit>, 
/**
 * `HEAD` liegt im Upstream; dann ist „Ergänzen“ gesperrt.
 */
headPushed: boolean, 
/**
 * Letzter erfolgreicher Fetch in diesem App-Lauf, ms seit 1970.
 */
lastFetchMs: number | null, error: string | null, };
