// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeKind } from "./ChangeKind";

/**
 * Eine uncommittete Datei im Ordner eines Eintrags, die nicht zu den eigenen Changes gehört.
 */
export type GitForeignFile = { 
/**
 * Relativ zum Ordner, mit Schrägstrichen.
 */
path: string, kind: ChangeKind, added: number, deleted: number, binary: boolean, };
