// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitLogCommit = { id: string, shortId: string, parents: Array<string>, author: string, 
/**
 * Sekunden seit 1970; serde schreibt eine JSON-Zahl, kein `bigint`.
 */
time: number, subject: string, 
/**
 * Aus `%D` mit vollen Namen (`refs/heads/x`, `refs/remotes/origin/x`, `tag: refs/tags/x`), ohne `HEAD`.
 */
refs: Array<string>, own: boolean, pushed: boolean, };
