// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitLogCommit } from "./GitLogCommit";

export type GitLog = { commits: Array<GitLogCommit>, incoming: Array<GitLogCommit>, };
