// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ein laufender Merge oder Rebase im Arbeitsordner, den Git mit Konflikten hat stehen lassen.
 */
export type GitOperation = "none" | "merge" | "rebase";
