// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ein eigener Commit der Session seit der Basis.
 */
export type GitOwnCommit = { id: string, 
/**
 * Die ersten 7 Zeichen von `id`.
 */
shortId: string, subject: string, 
/**
 * Im Upstream enthalten; ohne Upstream `false`.
 */
pushed: boolean, 
/**
 * Relativ zum Ordner, mit Schrägstrichen.
 */
files: Array<string>, };
