// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitBusySession } from "./GitBusySession";
import type { GitEntryStatus } from "./GitEntryStatus";

export type GitSessionStatus = { 
/**
 * Reihenfolge wie `SessionChanges.repositories`.
 */
entries: Array<GitEntryStatus>, 
/**
 * Sessions des Vorhabens in `Starting`, `Running` oder `Waiting`.
 */
busy: Array<GitBusySession>, };
