// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Was mit offenen Änderungen beim Branch-Wechsel geschieht.
 */
export type GitSwitchMode = "plain" | "stash";
