// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepositoryKind } from "./RepositoryKind";

/**
 * Ein Repository, das die App kennt, samt Zustand für die Auswahl.
 */
export type KnownRepository = { id: string, name: string, path: string, 
/**
 * `Git`, wenn `<path>\.git` existiert, sonst `Folder`.
 */
kind: RepositoryKind, 
/**
 * Anzahl der Skills unter `.claude/skills` im Repository.
 */
skillCount: number, 
/**
 * Der Ordner fehlt.
 */
isMissing: boolean, };
