// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ein Repository, das die App kennt, samt Zustand für die Auswahl.
 */
export type KnownRepository = { id: string, name: string, path: string, 
/**
 * Anzahl der Skills unter `.claude/skills` im Repository.
 */
skillCount: number, 
/**
 * Der Ordner fehlt oder ist kein Git-Repository mehr.
 */
isMissing: boolean, };
