// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeKind } from "./ChangeKind";

export type LineStat = { kind: ChangeKind, added: number, deleted: number, 
/**
 * Git zählt keine Zeilen; `added` und `deleted` sind dann 0.
 */
binary: boolean, };
