// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalModel } from "./LocalModel";

/**
 * Was die Einstellungsseite zeigt. Ein nicht erreichbares LM Studio ist kein Command-Fehler,
 * sondern `error`.
 */
export type LocalModels = { baseUrl: string, models: Array<LocalModel>, error: string | null, };
