// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalModelKind } from "./LocalModelKind";

export type LocalModel = { id: string, kind: LocalModelKind, isLoaded: boolean, 
/**
 * Nur bei geladenem Modell.
 */
loadedContextLength: number | null, maxContextLength: number, };
