// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpAction } from "./McpAction";

export type McpActionError = { server: string, action: McpAction, text: string, };
