// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Eine gestartete Anmeldung, deren Abschluss noch nicht in `mcp_status` zu sehen ist.
 */
export type McpAuthWait = { server: string, 
/**
 * Die Anmeldeseite; immer `https://`.
 */
url: string, 
/**
 * `true`: die Kommandozeile wartet auf den Rücksprung und verbindet selbst neu. `false` (claude.ai): danach neu verbinden.
 */
callbackExpected: boolean, };
