// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerStatus } from "./McpServerStatus";

export type McpServer = { name: string, status: McpServerStatus, 
/**
 * Herkunft wie von der Kommandozeile gemeldet (`user`, `project`, `local`, `claudeai`, `dynamic` …); leer, wenn sie fehlt.
 */
scope: string, 
/**
 * Kurzform der Verbindung: `stdio · comfy-mcp.exe`, `HTTPS · mcp.alphavantage.co`; leer, wenn nichts davon lesbar ist.
 */
connection: string, 
/**
 * Werkzeugnamen in der Reihenfolge der Kommandozeile; leer, solange der Server nicht verbunden ist.
 */
tools: Array<string>, 
/**
 * Fehlertext der Kommandozeile bei `Failed`.
 */
error: string | null, };
