// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Zustand eines Servers laut `mcp_status`. Unbekannte Werte der Kommandozeile → `Unknown`.
 */
export type McpServerStatus = "connected" | "pending" | "failed" | "needsAuth" | "disabled" | "unknown";
