// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Woher die Modellanfragen der Agenten kommen (ADR 016). `ClaudeCodeLocal` startet dieselbe
 * Claude-Kommandozeile, schickt die Anfragen aber an LM Studio.
 */
export type OperatingMode = "claude" | "claudeCodeLocal";
