// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Die Antwort von Claude auf `PROJECT_SCHEMA`; gespeichert als JSON in `projects.tldr`.
 */
export type ProjectTldr = { 
/**
 * Zwei Sätze.
 */
summary: string, status: string, 
/**
 * Leer = nichts offen.
 */
open: string, 
/**
 * Leer = unklar.
 */
next: string, openNeedsUser: boolean, };
