// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectSummary = { id: string, name: string, createdAt: number, 
/**
 * Namen der Repositories in Positions-Reihenfolge; für alle Sessions des Vorhabens gleich.
 */
repositoryNames: Array<string>, };
