// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectSessionTldr } from "./ProjectSessionTldr";
import type { ProjectTldr } from "./ProjectTldr";

export type ProjectTldrView = { tldr: ProjectTldr | null, createdAt: number | null, 
/**
 * Aus wie vielen Session-TL;DRs es entstand.
 */
sourceCount: number, isRunning: boolean, error: string | null, 
/**
 * Alle Sessions des Vorhabens, nach Nummer.
 */
sessions: Array<ProjectSessionTldr>, };
