// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileChange } from "./FileChange";

export type RepositoryChanges = { 
/**
 * Wie `session_repositories.position`.
 */
position: number, name: string, branch: string, baseRef: string, 
/**
 * Commits von der Basis bis `HEAD`.
 */
commitCount: number, 
/**
 * Nach `path` sortiert (Byte-Reihenfolge).
 */
files: Array<FileChange>, 
/**
 * Gesetzt: `files` ist leer und die Zahl der Commits 0.
 */
error: string | null, };
