// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ob ein bekannter Ordner ein Git-Repository ist (ADR 018).
 */
export type RepositoryKind = "git" | "folder";
