// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Das Ergebnis eines Retro-Laufs: wo die Dateien liegen und wie viele Sessions einbezogen wurden.
 */
export type RetroExport = { 
/**
 * Relativ zum Workspace, mit `/` getrennt, z. B. `.retro/lauf-1759830000000`.
 */
folder: string, sessionCount: number, 
/**
 * Sessions, deren Mini-Retro fehlschlug (stehen mit Fehlertext in `befunde.md`).
 */
failedCount: number, };
