// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffLineKind } from "./DiffLineKind";

/**
 * Ein Review-Kommentar zu einer Diff-Zeile der Changes-Ansicht; geht mit `chat_send` an den Agenten.
 */
export type ReviewComment = { 
/**
 * `RepositoryChanges.key`: `"<Position>"`, `"<Position>/<Ordner>"` oder `"<Position>:<Ordner>"`.
 */
repositoryKey: string, 
/**
 * `RepositoryChanges.name`, nur zur Anzeige und als Ersatz, wenn der Schlüssel nicht mehr auflösbar ist.
 */
repositoryName: string, 
/**
 * `FileChange.path`: relativ zum Repository bzw. Worktree, mit `/`.
 */
path: string, 
/**
 * `Added`, `Deleted` oder `Context` — nie `Hunk`.
 */
kind: DiffLineKind, 
/**
 * Neue Nummer; bei `Deleted` die alte.
 */
line: number, 
/**
 * Zeilentext ohne Vorzeichen, wie `DiffLine.text`.
 */
code: string, 
/**
 * Der Kommentar, getrimmt, nicht leer.
 */
text: string, };
