// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScratchpadEntry = { 
/**
 * Relativ zum Scratchpad, mit `/` getrennt.
 */
path: string, isDir: boolean, 
/**
 * serde schreibt eine JSON-Zahl, kein `bigint`; bis 2^53 Bytes ist sie in TypeScript genau.
 */
sizeBytes: number, modifiedMs: number, };
