// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScratchpadEntry } from "./ScratchpadEntry";

export type ScratchpadListing = { 
/**
 * `None`, solange der Agent der Session noch nie lief.
 */
dir: string | null, entries: Array<ScratchpadEntry>, truncated: boolean, };
