// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Die Antwort von Claude auf `SESSION_SCHEMA`; gespeichert als JSON in `sessions.tldr`.
 */
export type SessionTldr = { 
/**
 * Ein Satz, höchstens 160 Zeichen.
 */
short: string, goal: string, done: string, 
/**
 * Leer = nichts läuft.
 */
ongoing: string, 
/**
 * Leer = nichts offen.
 */
open: string, openNeedsUser: boolean, };
