// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionTldr } from "./SessionTldr";

export type SessionTldrView = { tldr: SessionTldr | null, 
/**
 * Millisekunden seit 1970.
 */
createdAt: number | null, 
/**
 * Anzahl Chat-Einträge, die das TL;DR kannte; 0 ohne TL;DR.
 */
seq: number, isRunning: boolean, error: string | null, 
/**
 * Haken der Einstiegsansicht: die erste Nachricht trägt das TL;DR des Vorhabens mit.
 */
carriesProjectTldr: boolean, };
