// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpActionError } from "./McpActionError";
import type { McpAuthWait } from "./McpAuthWait";
import type { McpServer } from "./McpServer";

export type SessionMcp = { 
/**
 * `None`: kein Stand (Agent läuft nicht oder die erste Antwort steht aus).
 */
servers: Array<McpServer> | null, 
/**
 * Namen der Server mit laufender Aktion.
 */
busy: Array<string>, 
/**
 * Fehler der letzten gescheiterten Aktion; die nächste Aktion löscht ihn.
 */
error: McpActionError | null, 
/**
 * Offene Anmeldung; `None`, wenn keine läuft.
 */
auth: McpAuthWait | null, 
/**
 * Millisekunden seit 1970, gesetzt beim Eintreffen der Liste.
 */
fetchedAt: number | null, isAgentRunning: boolean, };
