// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effort } from "./Effort";
import type { Mode } from "./Mode";
import type { ModelId } from "./ModelId";
import type { SessionStatus } from "./SessionStatus";

export type SessionSummary = { id: string, name: string, status: SessionStatus, model: ModelId, effort: Effort, mode: Mode, createdAt: number, 
/**
 * Summe der abgeschlossenen Laufzeiten; ein laufender Abschnitt kommt über `running_since` dazu.
 */
runningMs: number, runningSince: number | null, contextUsed: number, contextWindow: number, };
