// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepositoryChanges } from "./RepositoryChanges";

export type SessionChanges = { 
/**
 * Je Session-Repository erst sein Eintrag, dann seine Ticket-Worktrees.
 */
repositories: Array<RepositoryChanges>, };
