// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effort } from "./Effort";
import type { Mode } from "./Mode";
import type { ModelId } from "./ModelId";
import type { SessionStatus } from "./SessionStatus";

export type SessionSummary = { id: string, name: string, 
/**
 * Anzeige-Status: solange ein Subagent nach der abgegebenen Antwort noch arbeitet, `Running`.
 */
status: SessionStatus, 
/**
 * Der Hauptagent hat abgegeben und wartet auf einen laufenden Subagenten; `status` ist dann `Running`.
 */
awaitingSubagent: boolean, model: ModelId, effort: Effort, mode: Mode, createdAt: number, 
/**
 * Summe der abgeschlossenen Laufzeiten; ein laufender Abschnitt kommt über `running_since` dazu.
 */
runningMs: number, runningSince: number | null, contextUsed: number, contextWindow: number, repositoryCount: number, projectId: string, 
/**
 * Laufende Nummer im Vorhaben, ab 1; angezeigt als `#N`.
 */
number: number, 
/**
 * Server mit Status `Failed` oder `NeedsAuth`; 0 ohne Liste.
 */
mcpProblems: number, 
/**
 * Letztes Senden des Users oder Abgeben des Agenten (Rückfrage, fertig, Fehler); beim Anlegen `created_at`.
 */
lastActivityAt: number, 
/**
 * Seit dem letzten Blick des Users hat der Agent abgegeben.
 */
unread: boolean, };
