// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepositoryChanges } from "./RepositoryChanges";

export type SessionChanges = { 
/**
 * In der Reihenfolge von `session_repositories`.
 */
repositories: Array<RepositoryChanges>, };
