// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextBreakdown } from "./ContextBreakdown";

export type SessionContext = { breakdown: ContextBreakdown | null, isAgentRunning: boolean, };
