// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorScheme } from "./ColorScheme";
import type { Effort } from "./Effort";
import type { Mode } from "./Mode";
import type { ModelId } from "./ModelId";

/**
 * Werte, die für die ganze App gelten. Modell, Modus und Denkaufwand gelten für die erste Session
 * eines neuen Vorhabens.
 */
export type Settings = { colorScheme: ColorScheme, defaultModel: ModelId, defaultEffort: Effort, defaultMode: Mode, };
