// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorScheme } from "./ColorScheme";
import type { Effort } from "./Effort";
import type { Mode } from "./Mode";
import type { ModelId } from "./ModelId";
import type { OperatingMode } from "./OperatingMode";

/**
 * Eine Änderung aus der Einstellungsseite. Modus und Denkaufwand ändern sich gemeinsam, weil sie
 * im selben Menü stehen.
 */
export type SettingsChange = { "kind": "colorScheme", value: ColorScheme, } | { "kind": "defaultModel", value: ModelId, } | { "kind": "defaultMode", mode: Mode, effort: Effort, } | { "kind": "operatingMode", value: OperatingMode, } | { "kind": "localModel", value: string, };
