// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Settings } from "./Settings";

/**
 * Was die Einstellungsseite zeigt: die Werte und die Ordner, die sie nur anzeigt.
 */
export type SettingsOverview = { settings: Settings, 
/**
 * Absolut: `<Benutzerordner>\.claude\skills`.
 */
userSkillsDir: string, 
/**
 * Skills des Benutzers ohne Befehle.
 */
userSkillCount: number, 
/**
 * Absolut: `<Benutzerordner>\.verwalter\workspaces`.
 */
workspacesDir: string, };
