// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Woher ein Skill oder Befehl stammt.
 */
export type SkillOrigin = { "kind": "user" } | { "kind": "repository", name: string, };
