// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillKind } from "./SkillKind";
import type { SkillOrigin } from "./SkillOrigin";

/**
 * Ein Eintrag des `/`-Menüs.
 */
export type SkillInfo = { name: string, description: string, kind: SkillKind, origin: SkillOrigin, };
