// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillOrigin } from "./SkillOrigin";

/**
 * Der Skill, den eine gesendete Nachricht aufruft; hängt am Chat-Eintrag.
 */
export type SkillRef = { name: string, origin: SkillOrigin, };
