// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Textvorschau einer Ausgabe oder Datei. `missing`: die Datei gibt es (noch) nicht;
 * `binary`: sie enthält ein NUL-Byte, `text` bleibt dann leer.
 */
export type TextPreview = { text: string, truncated: boolean, missing: boolean, binary: boolean, };
