// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TldrChangedEvent = { projectId: string, 
/**
 * `None`: das TL;DR des Vorhabens selbst.
 */
sessionId: string | null, };
