// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ein unterbrochener Aufruf kann trotzdem ausgeführt worden sein —
 * deshalb gibt es `Interrupted` und bewusst kein „nicht ausgeführt“.
 */
export type ToolState = "running" | "done" | "failed" | "interrupted";
