// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageSnapshot } from "./UsageSnapshot";

export type UsageStatus = { 
/**
 * Der letzte erfolgreiche Stand; ein fehlgeschlagener Abruf lässt ihn stehen.
 */
snapshot: UsageSnapshot | null, 
/**
 * Fehler des letzten Abrufs, `None` nach einem Erfolg.
 */
error: string | null, isLoading: boolean, };
