// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageShare = { 
/**
 * Bei Verhalten der Schlüssel (`long_context`, `cron`, `high_parallel`), bei Skills der Name.
 */
key: string, 
/**
 * 0–100.
 */
percent: number, };
