// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageBreakdown } from "./UsageBreakdown";
import type { UsageLimit } from "./UsageLimit";

export type UsageSnapshot = { 
/**
 * `subscription_type`, z.B. `pro`.
 */
plan: string | null, limits: Array<UsageLimit>, day: UsageBreakdown | null, week: UsageBreakdown | null, 
/**
 * Millisekunden seit 1970; gesetzt beim Eintreffen im Core.
 */
fetchedAt: number, };
