// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageShare } from "./UsageShare";

export type UsageBreakdown = { requestCount: number, sessionCount: number, behaviors: Array<UsageShare>, skills: Array<UsageShare>, };
