// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageLimit = { 
/**
 * Beobachtet `session` (5-Stunden-Fenster) und `weekly_all` (Woche).
 */
kind: string, 
/**
 * 0–100.
 */
percent: number, 
/**
 * Beobachtet nur `normal`; fehlt der Wert, steht hier `normal`.
 */
severity: string, 
/**
 * ISO-8601 mit Zeitzone, unverändert von der Kommandozeile.
 */
resetsAt: string | null, };
