// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoiceModelState } from "./VoiceModelState";

export type VoiceModelEvent = { state: VoiceModelState, 
/**
 * Nur beim Wechsel nach `Missing` wegen eines fehlgeschlagenen Downloads gesetzt
 * (Text = `CommandError::VoiceDownload(..).to_string()`); bei Abbruch durch den Nutzer `None`.
 */
error: string | null, };
