// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Der gesamte bisher erkannte Text des laufenden Diktats (nicht nur der neue Abschnitt),
 * getrimmt, nie leer. Die Oberfläche ersetzt damit ihre Vorschau, statt Stücke anzuhängen.
 */
export type VoicePartialEvent = { text: string, };
