// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pegel von 0.0 bis 1.0 (RMS der letzten ~50 ms).
 */
export type VoiceLevelEvent = { level: number, };
